name: localregex
description: Collection of regex patterns commonly used in Zimbabwe
version: 3.0.0
homepage: https://www.iamngoni.co.zw/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

